DROP TABLE IF EXISTS `user`;
CREATE TABLE `user` (
  `id` INT NOT NULL AUTO_INCREMENT PRIMARY KEY COMMENT '用户ID',
  `username` VARCHAR(20) NOT NULL COMMENT '用户名',
  `password` VARCHAR(40) NOT NULL COMMENT '用户密码',
  `avatar` TEXT DEFAULT NULL COMMENT '用户头像',
  `background` TEXT DEFAULT NULL COMMENT '用户背景图',
  `nickname` VARCHAR(20) DEFAULT NULL COMMENT '用户昵称',
  `birthday` DATE DEFAULT NULL COMMENT '用户生日',
  `role_id` INT DEFAULT NULL COMMENT '用户角色',
  `gender` VARCHAR(4) DEFAULT NULL COMMENT '性别',
  `community_id` INT DEFAULT NULL COMMENT '社区ID',
  `house_id` INT DEFAULT NULL COMMENT '住房ID',
  `tel` VARCHAR(13) DEFAULT NULL COMMENT '用户手机号',
  `create_time` DATETIME DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `update_time` DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  `is_deleted` BOOLEAN DEFAULT FALSE COMMENT '删除标记位',
  UNIQUE KEY `user_username_uindex` (`username`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT '用户';

DROP TABLE IF EXISTS `role`;
CREATE TABLE `role` (
  `id` INT NOT NULL AUTO_INCREMENT PRIMARY KEY COMMENT '角色ID',
  `name` VARCHAR(20) DEFAULT NULL COMMENT '角色名称',
  `description` VARCHAR(40) DEFAULT NULL COMMENT '角色描述',
  `create_time` DATETIME DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `update_time` DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  `is_deleted` BOOLEAN DEFAULT FALSE COMMENT '删除标记位'
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT '用户角色';

DROP TABLE IF EXISTS `community`;
CREATE TABLE `community` (
  `id` INT NOT NULL AUTO_INCREMENT PRIMARY KEY COMMENT '社区ID',
  `property_id` INT DEFAULT NULL COMMENT '物业ID',
  `name` VARCHAR(20) DEFAULT NULL COMMENT '社区名称',
  `address` VARCHAR(40) DEFAULT NULL COMMENT '社区地址',
  `third_party_id` VARCHAR(80) DEFAULT NULL COMMENT '第三方ID',
  `code` VARCHAR(40) DEFAULT NULL COMMENT '社区码',
  `cooperation_time` DATETIME DEFAULT NULL COMMENT '合作时间',
  `create_time` DATETIME DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `update_time` DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  `is_deleted` BOOLEAN DEFAULT FALSE COMMENT '删除标记位'
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT '社区';

DROP TABLE IF EXISTS `property`;
CREATE TABLE `property` (
  `id` INT NOT NULL AUTO_INCREMENT PRIMARY KEY COMMENT '物业ID',
  `name` VARCHAR(20) DEFAULT NULL COMMENT '物业名称',
  `tel` VARCHAR(13) DEFAULT NULL COMMENT '联系电话',
  `create_time` DATETIME DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `update_time` DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  `is_deleted` BOOLEAN DEFAULT FALSE COMMENT '删除标记位'
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT '物业';

DROP TABLE IF EXISTS `house`;
CREATE TABLE `house` (
  `id` INT NOT NULL AUTO_INCREMENT PRIMARY KEY COMMENT '住房ID',
  `community_id` INT DEFAULT NULL COMMENT '社区ID',
  `owner_name` VARCHAR(20) DEFAULT NULL COMMENT '户主姓名',
  `building_id` INT DEFAULT NULL COMMENT '楼房栋数',
  `unit_id` INT DEFAULT NULL COMMENT '单元号',
  `room_id` INT DEFAULT NULL COMMENT '门牌号',
  `property_fee` DOUBLE(6, 2) DEFAULT NULL COMMENT '住房每年对应物业费用',
  `area` DOUBLE(6, 2) DEFAULT NULL COMMENT '面积',
  `create_time` DATETIME DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `update_time` DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  `is_deleted` BOOLEAN DEFAULT FALSE COMMENT '删除标记位',
   UNIQUE KEY `house_community_id_building_id_unit_id_room_id_uindex` (`community_id`,`building_id`,`unit_id`,`room_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT '小区住房';

DROP TABLE IF EXISTS `board_message`;
CREATE TABLE `board_message` (
  `id` INT NOT NULL AUTO_INCREMENT PRIMARY KEY COMMENT '公告栏消息ID',
  `user_id` INT DEFAULT NULL COMMENT '用户ID',
  `is_top` TINYINT DEFAULT NULL COMMENT '消息是否置顶',
  `content` TEXT DEFAULT NULL COMMENT '消息正文',
  `top_start_time` DATETIME DEFAULT NULL COMMENT '置顶开始时间',
  `top_end_time` DATETIME DEFAULT NULL COMMENT '置顶结束时间',
  `source` VARCHAR(20) DEFAULT NULL COMMENT '消息来源设备',
  `like_count` INT DEFAULT NULL COMMENT '点赞统计',
  `comment_count` INT DEFAULT NULL COMMENT '评论统计',
  `repost_count` INT DEFAULT NULL COMMENT '转发统计',
  `post_time` DATETIME DEFAULT NULL COMMENT '发送时间',
  `create_time` DATETIME DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `update_time` DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  `is_deleted` BOOLEAN DEFAULT FALSE COMMENT '删除标记位'
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT '公告栏消息';

DROP TABLE IF EXISTS `payment`;
CREATE TABLE `payment` (
  `id` INT NOT NULL AUTO_INCREMENT PRIMARY KEY COMMENT '缴费ID',
  `name` VARCHAR(20) DEFAULT NULL COMMENT '缴费名称',
  `user_id` INT DEFAULT NULL COMMENT '用户ID',
  `type` INT DEFAULT NULL COMMENT '缴费类别',
  `deadline` DATETIME DEFAULT NULL COMMENT '缴费截止日期',
  `transaction_id` INT DEFAULT NULL COMMENT '交易ID',
  `amount` DOUBLE(6, 2) DEFAULT NULL COMMENT '缴费金额',
  `pay_time` DATETIME DEFAULT NULL COMMENT '缴费时间',
  `remark` VARCHAR(40) DEFAULT NULL COMMENT '备注',
  `create_time` DATETIME DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `update_time` DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  `is_deleted` BOOLEAN DEFAULT FALSE COMMENT '删除标记位'
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT '缴费';

DROP TABLE IF EXISTS `transaction`;
CREATE TABLE `transaction` (
  `id` INT NOT NULL AUTO_INCREMENT PRIMARY KEY COMMENT '交易ID',
  `platform_id` INT DEFAULT NULL COMMENT '交易平台ID',
  `amount` DOUBLE(6, 2) DEFAULT NULL COMMENT '缴费金额',
  `code` VARCHAR(80) DEFAULT NULL COMMENT '交易号',
  `trading_time` DATETIME DEFAULT NULL COMMENT '交易时间',
  `status` INT DEFAULT NULL COMMENT '交易状态',
  `create_time` DATETIME DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `update_time` DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  `is_deleted` BOOLEAN DEFAULT FALSE COMMENT '删除标记位'
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT '交易';

DROP TABLE IF EXISTS `repair`;
CREATE TABLE `repair` (
  `id` INT NOT NULL AUTO_INCREMENT PRIMARY KEY COMMENT '报修ID',
  `user_id` INT DEFAULT NULL COMMENT '用户ID',
  `community_id` INT DEFAULT NULL COMMENT '社区ID',
  `house_id` INT DEFAULT NULL COMMENT '住房ID',
  `type` INT DEFAULT NULL COMMENT '报修类别',
  `reporter` VARCHAR(20) DEFAULT NULL COMMENT '报修人',
  `post_time` DATETIME DEFAULT NULL COMMENT '报修时间',
  `expect_handle_time` DATETIME DEFAULT NULL COMMENT '期望解决时间',
  `reporter_tel` VARCHAR(13) DEFAULT NULL COMMENT '预留手机号码',
  `description` VARCHAR(80) DEFAULT NULL COMMENT '情况描述',
  `status` INT DEFAULT NULL COMMENT '报修状态',
  `create_time` DATETIME DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `update_time` DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  `is_deleted` BOOLEAN DEFAULT FALSE COMMENT '删除标记位'
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT '报修';

DROP TABLE IF EXISTS `property_fee`;
CREATE TABLE `property_fee` (
  `id` INT NOT NULL AUTO_INCREMENT PRIMARY KEY COMMENT '物业费ID',
  `house_id` INT DEFAULT NULL COMMENT '住房ID',
  `community_id` INT DEFAULT NULL COMMENT '社区ID',
  `status` INT DEFAULT NULL COMMENT '物业费支付状态',
  `year` YEAR DEFAULT NULL COMMENT '物业费年份',
  `amount` DOUBLE(6, 2) DEFAULT NULL COMMENT '总费用',
  `deadline` DATETIME DEFAULT NULL COMMENT '截止时间',
  `pay_time` DATETIME DEFAULT NULL COMMENT '支付时间',
  `create_time` DATETIME DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `update_time` DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  `is_deleted` BOOLEAN DEFAULT FALSE COMMENT '删除标记位'
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT '物业费';
