CREATE TABLE `country` (
  `id` INT NOT NULL AUTO_INCREMENT PRIMARY KEY COMMENT '国家ID',
  `name` INT DEFAULT NULL COMMENT '国家',
  `abbr` INT DEFAULT NULL COMMENT '',
  `status` INT DEFAULT NULL COMMENT '物业费支付状态',
  `year` YEAR DEFAULT NULL COMMENT '物业费年份',
  `amount` DOUBLE(6, 2) DEFAULT NULL COMMENT '总费用',
  `deadline` DATETIME DEFAULT NULL COMMENT '截止时间',
  `pay_time` DATETIME DEFAULT NULL COMMENT '支付时间',
  `create_time` DATETIME DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `update_time` DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  `is_deleted` BOOLEAN DEFAULT FALSE COMMENT '删除标记位'
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT '物业费';